# Generated by Django 4.2.7 on 2025-11-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa para cotizaciones y documentos', null=True, upload_to='logos/'),
        ),
    ]
