# Generated by Django 4.2.9 on 2026-03-02 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
