# Generated by Django 4.2.9 on 2026-03-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='firma_aprobado',
            field=models.ImageField(blank=True, help_text='Firma digital - Aprobado por', null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='firma_elaborado',
            field=models.ImageField(blank=True, help_text='Firma digital - Elaborado por', null=True, upload_to='firmas/'),
        ),
    ]
