# Generated by Django 4.2.7 on 2026-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_tipo_cambio_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modo_inventario',
            field=models.CharField(choices=[('con_stock', 'Con inventario'), ('sin_stock', 'Sin inventario (back-to-back)')], default='con_stock', help_text='con_stock: la empresa maneja inventario (reserva/descuenta stock). sin_stock: modelo back-to-back, nunca mueve inventario y el menú de Inventario se oculta.', max_length=20, verbose_name='Modo de inventario'),
        ),
    ]
