# Generated by Django 4.2.7 on 2025-04-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
