# Generated by Django 4.2.7 on 2025-04-24 23:12

import apps.ventas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_delete_cotizacion_delete_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='igv_incluido',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.ventas.models.comprobante_upload_to)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('ticket', 'Ticket'), ('otro', 'Otro')], max_length=50)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_pago', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
            },
        ),
    ]
