# Generated by Django 4.2.7 on 2025-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_igv_incluido_comprobantepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='comprobante',
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
