# Generated by Django 4.2.7 on 2025-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_venta_comprobante_alter_venta_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='ventas/comprobantes/'),
        ),
    ]
