# Generated by Django 4.2.7 on 2025-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('ventas', '0005_venta_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='numero_orden',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'documento')},
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('cliente', 'numero_factura')},
        ),
        migrations.AlterUniqueTogether(
            name='ordenventa',
            unique_together={('empresa', 'numero_orden')},
        ),
    ]
