# Generated by Django 4.2.7 on 2025-05-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_factura_numero_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('dni', 'DNI'), ('ruc', 'RUC')], default='dni', max_length=10),
        ),
    ]
