# Generated by Django 4.2.7 on 2025-05-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('credito_30', 'Crédito 30 días'), ('credito_60', 'Crédito 60 días')], default='efectivo', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='ventas/pagos/')),
                ('notas', models.TextField(blank=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
        ),
    ]
