# Generated by Django 4.2.7 on 2025-05-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_venta_estado_pago_pagoventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoventa',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Pago de Venta', 'verbose_name_plural': 'Pagos de Ventas'},
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='ventas/pagos/', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('credito_30', 'Crédito 30 días'), ('credito_60', 'Crédito 60 días')], max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta', verbose_name='Venta'),
        ),
    ]
