# Generated by Django 4.2.7 on 2025-05-26 18:05

from django.db import migrations, models
from django.db.models import Sum

def actualizar_pagos_total(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    for venta in Venta.objects.all():
        total_pagado = venta.pagos.aggregate(total=Sum('monto'))['total'] or 0
        venta.pagos_total = total_pagado
        venta.save()

def revertir_pagos_total(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    Venta.objects.all().update(pagos_total=0)

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_pagoventa_options_alter_pagoventa_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagos_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(actualizar_pagos_total, revertir_pagos_total),
    ]
