# Generated by Django 4.2.7 on 2025-05-27 17:45

from django.db import migrations, models

def migrar_estado_pago_a_tipo_venta(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    for venta in Venta.objects.all():
        # Mapear estado_pago anterior a nuevo tipo_venta y metodo_pago
        if venta.estado_pago in ['credito_30', 'credito_60']:
            venta.tipo_venta = venta.estado_pago
            venta.metodo_pago = None  # Se establecerá cuando se registre el pago
        else:
            venta.tipo_venta = 'contado'
            venta.metodo_pago = venta.estado_pago
        venta.save()

def revertir_migracion(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    for venta in Venta.objects.all():
        if venta.tipo_venta in ['credito_30', 'credito_60']:
            venta.estado_pago = venta.tipo_venta
        else:
            venta.estado_pago = venta.metodo_pago or 'efectivo'
        venta.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_pagos_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='updated_at',
            new_name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(
                choices=[
                    ('contado', 'Contado'),
                    ('credito_30', 'Crédito 30 días'),
                    ('credito_60', 'Crédito 60 días')
                ],
                default='contado',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(
                choices=[
                    ('efectivo', 'Efectivo'),
                    ('transferencia', 'Transferencia'),
                    ('tarjeta', 'Tarjeta'),
                    ('cheque', 'Cheque')
                ],
                null=True,
                blank=True,
                max_length=20
            ),
        ),
        migrations.RunPython(
            migrar_estado_pago_a_tipo_venta,
            revertir_migracion
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado_pago',
        ),
    ]
