# Generated by Django 4.2.7 on 2025-05-27 17:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.core.validators import MinValueValidator

def corregir_numeros_duplicados(apps, schema_editor):
    Venta = apps.get_model('ventas', 'Venta')
    # Obtener todas las ventas ordenadas por fecha
    ventas = Venta.objects.all().order_by('fecha_emision', 'id')
    numeros_usados = set()
    
    for venta in ventas:
        # Si el número ya existe, generar uno nuevo
        if venta.numero in numeros_usados:
            # Encontrar el próximo número disponible
            num = 1
            while f"V-{str(num).zfill(6)}" in numeros_usados:
                num += 1
            nuevo_numero = f"V-{str(num).zfill(6)}"
            venta.numero = nuevo_numero
            venta.save()
        numeros_usados.add(venta.numero)

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_actualizar_modelo_venta_con_tipo_venta'),
    ]

    operations = [
        # Primero eliminar la restricción única existente
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together=set(),
        ),
        
        # Ejecutar la función para corregir números duplicados
        migrations.RunPython(
            corregir_numeros_duplicados,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Luego aplicar los cambios en los campos
        migrations.AlterField(
            model_name='pagoventa',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
