# Generated by Django 4.2.7 on 2025-05-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_actualizar_modelo_pago_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoventa',
            name='metodo_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de Pago'),
        ),
    ]
