# Generated by Django 4.2.7 on 2026-02-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_add_moneda_to_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='modo_venta',
            field=models.CharField(choices=[('stock', 'Desde Stock (Producto Terminado)'), ('pedido', 'A Pedido (Descontar Materias Primas)')], default='stock', help_text='Stock: descuenta productos terminados. Pedido: descuenta materias primas directamente.', max_length=20, verbose_name='Modo de Venta'),
        ),
    ]
