# Generated by Django 4.2.7 on 2026-09-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_controla_stock'),
        ('ventas', '0016_add_modo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='origen',
            field=models.CharField(blank=True, choices=[('stock', 'Desde stock (reserva/descuenta inventario)'), ('pedido_proveedor', 'A pedido de proveedor (nunca mueve inventario)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
