# Generated by Django 4.2.7 on 2026-10-01 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0019_set_db_defaults_columnas_nuevas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_operativo',
            field=models.CharField(choices=[('pendiente_compra', 'Pendiente de compra'), ('comprado', 'Comprado'), ('recibido', 'Recibido'), ('entregado', 'Entregado'), ('esperando_oc_nr', 'Esperando OC/NR del cliente'), ('facturado', 'Facturado'), ('cobrado', 'Cobrado')], default='pendiente_compra', max_length=30, verbose_name='Estado operativo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_operativo_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialEstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estado_venta', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_operativo', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Historial de Estado Operativo de Venta',
                'verbose_name_plural': 'Historial de Estados Operativos de Venta',
                'ordering': ['-fecha'],
            },
        ),
    ]
