# Generated by Django 4.2.7 on 2026-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_backfills_f3_estado_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_venta_empresa_numero'),
        ),
    ]
