# Generated by Django 4.2.9 on 2026-06-01 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_empresa_tipo_cambio_usd'),
        ('ventas', '0016_add_modo_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_traslado', models.DateField()),
                ('motivo', models.CharField(choices=[('ingreso_reparacion', 'Ingreso por Reparación'), ('devolucion_cliente', 'Devolución a Cliente'), ('traslado_tecnico', 'Traslado Técnico'), ('otro', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('en_proceso', 'En Proceso'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('nombre_destinatario', models.CharField(max_length=200)),
                ('ruc_destinatario', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion_origen', models.CharField(max_length=500)),
                ('direccion_destino', models.CharField(max_length=500)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_remision', to='ventas.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_remision', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Guía de Remisión',
                'verbose_name_plural': 'Guías de Remisión',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=50)),
                ('estado_ingreso', models.CharField(blank=True, max_length=200, null=True)),
                ('accesorios', models.TextField(blank=True, null=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guias.guiaremision')),
            ],
            options={
                'verbose_name': 'Ítem de Guía',
                'verbose_name_plural': 'Ítems de Guía',
                'ordering': ['numero_item'],
                'unique_together': {('guia', 'numero_item')},
            },
        ),
    ]
