# Generated by Django 4.2.7 on 2026-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='tipo',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('venta', 'Venta')], default='servicio', max_length=10),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='motivo',
            field=models.CharField(choices=[('ingreso_reparacion', 'Ingreso por Reparación'), ('devolucion_cliente', 'Devolución a Cliente'), ('traslado_tecnico', 'Traslado Técnico'), ('venta', 'Despacho de Venta'), ('otro', 'Otro')], max_length=30),
        ),
    ]
