# Generated by Django 4.2.9 on 2025-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiaction',
            name='datos',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='aiaction',
            name='resultado',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='aiaction',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En Progreso'), ('completed', 'Completado'), ('completed_with_errors', 'Completado con Errores'), ('failed', 'Fallido')], default='in_progress', max_length=25),
        ),
    ]
