# Generated by Django 4.2.7 on 2025-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_aiaction_datos_alter_aiaction_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
