# Generated by Django 4.2.7 on 2025-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_conversation_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_from_assistant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tipo',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Nueva Conversación', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], default='user', max_length=10),
        ),
    ]
