# Generated by Django 4.2.9 on 2026-03-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('ventas', 'Ventas'), ('cotizaciones', 'Cotizaciones'), ('cuentas_cobrar', 'Cuentas por Cobrar'), ('compras', 'Compras'), ('inventario', 'Inventario'), ('produccion', 'Producción'), ('reportes', 'Reportes'), ('configuracion', 'Configuración'), ('dashboard', 'Dashboard')], max_length=50)),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
                'db_table': 'core_permiso_usuario',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
