# Generated by Django 4.2.7 on 2025-11-05 23:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0015_add_moneda_to_venta'),
        ('inventario', '0007_add_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de cotización (ej: COT-00000001)', max_length=20, unique=True)),
                ('asunto', models.CharField(help_text='Asunto o título de la cotización', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la cotización')),
                ('fecha_aceptacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida a Venta')], default='borrador', max_length=20)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)')], default='PEN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('incluye_igv', models.BooleanField(default=True)),
                ('porcentaje_igv', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Porcentaje de IGV (por defecto 18%)', max_digits=5)),
                ('forma_pago', models.CharField(default='Contado', max_length=100)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_entrega', models.TextField(blank=True, null=True)),
                ('validez_oferta', models.CharField(default='30 días', max_length=100)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para el cliente', null=True)),
                ('terminos_condiciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ventas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='empresas.empresa')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'db_table': 'detalles_cotizacion',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['empresa', 'estado'], name='cotizacione_empresa_bd7bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente'], name='cotizacione_cliente_ef8f00_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_emision'], name='cotizacione_fecha_e_36acc2_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero'], name='cotizacione_numero_4c8e78_idx'),
        ),
    ]
