# Generated by Django 4.2.7 on 2025-11-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='pago_facturas',
            field=models.CharField(blank=True, help_text='Horario de pago de facturas', max_length=200, null=True),
        ),
    ]
