# Generated by Django 4.2.7 on 2026-06-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_precios_incluyen_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del contacto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del contacto'),
        ),
    ]
