# Generated by Django 4.2.7 on 2026-09-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_ordencompra_cotizacion_origen_ordencompra_venta'),
        ('cotizaciones', '0004_cotizacion_contacto_nombre_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('precio', 'Precio'), ('plazo', 'Plazo'), ('competidor', 'Competidor'), ('sin_presupuesto', 'Sin presupuesto'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo_nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota del motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de compra estimado por unidad. Uso interno (margen y OC).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_cotizacion', to='compras.proveedor'),
        ),
    ]
