# Generated by Django 4.2.7 on 2026-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_cotizacion_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(help_text='Número de cotización (ej: COT-00000001)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_cotizacion_empresa_numero'),
        ),
    ]
