# Generated by Django 4.2.7 on 2026-10-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_alter_cotizacion_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='TC venta SBS de la fecha de emisión. PEN = 1.0. Se fija al emitir y no cambia.', max_digits=10, null=True, verbose_name='Tipo de cambio'),
        ),
    ]
