# Generated by Django 4.2.9 on 2026-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comercial', 'Staff Comercial'), ('produccion', 'Staff Producción'), ('almacen', 'Almacén'), ('contador', 'Contador'), ('readonly', 'Solo Lectura'), ('personalizado', 'Personalizado')], default='readonly', help_text='Rol principal del usuario. Usa "personalizado" para permisos granulares.', max_length=20),
        ),
    ]
