# Generated by Django 4.2.9 on 2026-06-01 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0008_change_numero_unique_per_empresa'),
        ('ventas', '0016_add_modo_venta'),
        ('guias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0003_cotizacion_precios_incluyen_igv'),
        ('empresas', '0005_empresa_tipo_cambio_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('fecha_cotizacion_enviada', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio_reparacion', models.DateField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('diagnostico_pendiente', 'Diagnóstico Pendiente'), ('diagnostico_completado', 'Diagnóstico Completado'), ('cotizacion_enviada', 'Cotización Enviada'), ('cotizacion_aprobada', 'Cotización Aprobada'), ('en_reparacion', 'En Reparación'), ('reparacion_completada', 'Reparación Completada'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='diagnostico_pendiente', max_length=30)),
                ('dias_sla', models.IntegerField(default=30)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='ventas.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio', to='cotizaciones.cotizacion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_servicio', to='empresas.empresa')),
                ('guia_remision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio', to='guias.guiaremision')),
                ('proveedor_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado_reportado', models.CharField(max_length=200)),
                ('fecha_entrega_prometida', models.DateField(blank=True, null=True)),
                ('notas', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='servicios.ordenservicio')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Proveedor',
                'verbose_name_plural': 'Seguimientos de Proveedor',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='servicios.ordenservicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estado_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado OS',
                'verbose_name_plural': 'Historial de Estados OS',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('falla_cliente', models.TextField(blank=True, null=True)),
                ('falla_diagnostico', models.TextField(blank=True, null=True)),
                ('falla_adicional', models.BooleanField(default=False)),
                ('estado_item', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_diagnostico', 'En Diagnóstico'), ('diagnosticado', 'Diagnosticado'), ('en_reparacion', 'En Reparación'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('costo_proveedor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margen', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('item_guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_orden_servicio', to='guias.itemguia')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='servicios.ordenservicio')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Servicio',
                'verbose_name_plural': 'Ítems de Orden de Servicio',
                'ordering': ['numero_item'],
                'unique_together': {('orden', 'numero_item')},
            },
        ),
    ]
