# Generated by Django 4.2.7 on 2025-12-18 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_logo'),
        ('inventario', '0008_producto_tipo_producto_alter_producto_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Código único de la orden (auto-generado)', max_length=20, unique=True, verbose_name='Número de Orden')),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, help_text='Cantidad que se planea producir', max_digits=10, verbose_name='Cantidad Planificada')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad real producida', max_digits=10, verbose_name='Cantidad Producida')),
                ('fecha_programada', models.DateField(help_text='Fecha en que se debe producir', verbose_name='Fecha Programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha y hora en que se inició la producción', null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora en que se finalizó la producción', null=True, verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('costo_mano_obra_real', models.DecimalField(decimal_places=2, default=0, help_text='Costo real de mano de obra', max_digits=10, verbose_name='Costo Mano de Obra Real')),
                ('costo_indirecto_real', models.DecimalField(decimal_places=2, default=0, help_text='Costos indirectos reales (CIF)', max_digits=10, verbose_name='Costo Indirecto Real')),
                ('tiempo_real', models.IntegerField(default=0, help_text='Tiempo real que tomó la producción en minutos', verbose_name='Tiempo Real (minutos)')),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones del operador', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen_destino', models.ForeignKey(help_text='Almacén donde ingresa el producto terminado', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_destino', to='inventario.almacen', verbose_name='Almacén de Destino')),
                ('almacen_insumos', models.ForeignKey(help_text='Almacén desde donde se consumen los insumos', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_consumo', to='inventario.almacen', verbose_name='Almacén de Insumos')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción de la receta', max_length=200, verbose_name='Nombre de la Receta')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de producto terminado que se obtiene con esta receta', max_digits=10, verbose_name='Cantidad Producida')),
                ('tiempo_estimado', models.IntegerField(default=0, help_text='Tiempo estimado de producción en minutos', verbose_name='Tiempo Estimado (minutos)')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo estimado de mano de obra directa', max_digits=10, verbose_name='Costo de Mano de Obra')),
                ('costo_indirecto', models.DecimalField(decimal_places=2, default=0, help_text='Costos indirectos de fabricación', max_digits=10, verbose_name='Costos Indirectos (CIF)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta receta está activa', verbose_name='Activa')),
                ('version', models.IntegerField(default=1, help_text='Número de versión de la receta', verbose_name='Versión')),
                ('notas', models.TextField(blank=True, help_text='Instrucciones adicionales para la producción', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_produccion', to='empresas.empresa')),
                ('producto_terminado', models.ForeignKey(help_text='Producto que se obtiene al ejecutar esta receta', on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='inventario.producto', verbose_name='Producto Terminado')),
            ],
            options={
                'verbose_name': 'Receta de Producción',
                'verbose_name_plural': 'Recetas de Producción',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'producto_terminado', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProductionWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_desperdiciada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Desperdiciada')),
                ('motivo', models.CharField(choices=[('PROCESS', 'Proceso Normal'), ('DAMAGED', 'Dañado/Defectuoso'), ('EXPIRED', 'Vencido/Caducado'), ('OTHER', 'Otro')], default='PROCESS', max_length=20, verbose_name='Motivo')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre la merma', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_produccion', to='inventario.producto', verbose_name='Producto/Insumo')),
            ],
            options={
                'verbose_name': 'Merma/Desperdicio',
                'verbose_name_plural': 'Mermas/Desperdicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, help_text='Cantidad producida en este lote/cierre parcial', max_digits=10, verbose_name='Cantidad Producida')),
                ('numero_lote', models.CharField(blank=True, help_text='Identificador del lote producido', max_length=50, verbose_name='Número de Lote')),
                ('fecha_produccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Producción')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre este lote', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Producción Parcial',
                'verbose_name_plural': 'Producciones Parciales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de insumos consumidos', max_digits=12, verbose_name='Costo de Materiales')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de Mano de Obra')),
                ('costo_indirecto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costos Indirectos (CIF)')),
                ('costo_mermas', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de desperdicios', max_digits=12, verbose_name='Costo de Mermas')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, help_text='Costo por unidad producida', max_digits=12, verbose_name='Costo Unitario')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot de la cantidad producida', max_digits=10, verbose_name='Cantidad Producida')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el costeo', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_produccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costeo', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Costeo de Producción',
                'verbose_name_plural': 'Costeos de Producción',
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.recetaproducto', verbose_name='Receta'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable de ejecutar la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Necesaria')),
                ('unidad_medida', models.CharField(help_text='Debe coincidir con la unidad del producto', max_length=20, verbose_name='Unidad de Medida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario del insumo al momento de crear la receta (referencia)', max_digits=10, verbose_name='Costo Unitario')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre este insumo', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='inventario.producto', verbose_name='Insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.recetaproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
                'unique_together': {('receta', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_teorica', models.DecimalField(decimal_places=2, help_text='Cantidad según la receta', max_digits=10, verbose_name='Cantidad Teórica')),
                ('cantidad_real', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad realmente consumida', max_digits=10, verbose_name='Cantidad Real')),
                ('merma', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad desperdiciada', max_digits=10, verbose_name='Merma')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Precio del insumo al momento del consumo', max_digits=10, verbose_name='Costo Unitario')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el consumo', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_produccion', to='inventario.producto', verbose_name='Insumo')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Consumo Real',
                'verbose_name_plural': 'Consumos Reales',
                'unique_together': {('orden_produccion', 'insumo')},
            },
        ),
    ]
