# Generated by Django 4.2.9 on 2026-02-24 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Orden creada'), ('inicio', 'Producción iniciada'), ('actualizacion_progreso', 'Progreso actualizado'), ('pausa', 'Producción pausada'), ('reanudacion', 'Producción reanudada'), ('consumo', 'Consumo registrado'), ('finalizacion', 'Orden finalizada'), ('cancelacion', 'Orden cancelada'), ('edicion', 'Orden editada'), ('otro', 'Otro evento')], default='otro', max_length=30)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('datos_adicionales', models.JSONField(blank=True, help_text='JSON con información extra del evento', null=True, verbose_name='Datos adicionales')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='produccion.ordenproduccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Orden',
                'verbose_name_plural': 'Historiales de Órdenes',
                'ordering': ['-fecha'],
            },
        ),
    ]
