# Generated by Django 4.2.7 on 2026-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_add_historial_orden_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='numero',
            field=models.CharField(help_text='Código auto-generado, único POR EMPRESA (ver Meta.constraints)', max_length=20, verbose_name='Número de Orden'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_ordenproduccion_empresa_numero'),
        ),
    ]
