# Generated by Django 4.2.9 on 2025-04-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
    ]
