# Generated by Django 4.2.7 on 2025-05-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20250414_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Total'),
        ),
    ]
