# Generated by Django 4.2.7 on 2025-06-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0004_alter_producto_sku_alter_categoria_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_entrada', 'Ajuste - Entrada'), ('ajuste_salida', 'Ajuste - Salida'), ('devolucion_compra', 'Devolución Compra'), ('devolucion_venta', 'Devolución Venta'), ('transferencia_entrada', 'Transferencia - Entrada'), ('transferencia_salida', 'Transferencia - Salida')], max_length=30)),
                ('tipo_documento', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste de Inventario'), ('devolucion_compra', 'Devolución de Compra'), ('devolucion_venta', 'Devolución de Venta'), ('transferencia', 'Transferencia'), ('inventario_inicial', 'Inventario Inicial')], max_length=30)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('cantidad_entrada', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cantidad_salida', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cantidad_saldo', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('costo_total_entrada', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('costo_total_salida', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('costo_saldo', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('compra_id', models.IntegerField(blank=True, null=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('ajuste_id', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('lote_referencia', models.CharField(blank=True, max_length=100)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['empresa', 'producto', 'fecha'], name='inventario__empresa_a19e01_idx'), models.Index(fields=['empresa', 'producto', 'tipo_movimiento'], name='inventario__empresa_3bda1c_idx'), models.Index(fields=['fecha'], name='inventario__fecha_f978ae_idx')],
            },
        ),
    ]
