# Generated by Django 4.2.7 on 2025-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(
                choices=[('PEN', 'Sol Peruano (S/)'), ('USD', 'Dólar Americano ($)')],
                default='PEN',
                max_length=3,
                verbose_name='Moneda'
            ),
        ),
    ]
