# Generated by Django 4.2.7 on 2025-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_add_moneda_to_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['sku'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kilo', 'Kilogramo'), ('gramo', 'Gramo'), ('decena', 'Decena'), ('docena', 'Docena'), ('centenar', 'Centenar'), ('millar', 'Millar')], default='unidad', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
