# Generated by Django 4.2.7 on 2025-12-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_add_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('RAW', 'Materia Prima / Insumo'), ('SEMIFINISHED', 'Semi-Terminado'), ('FINISHED', 'Producto Terminado')], default='RAW', help_text='Clasificación del producto para producción', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kilo', 'Kilogramo'), ('gramo', 'Gramo'), ('litro', 'Litro'), ('metro', 'Metro'), ('decena', 'Decena'), ('docena', 'Docena'), ('centenar', 'Centenar'), ('millar', 'Millar')], default='unidad', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
