# Generated by Django 4.2.7 on 2026-02-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
        ('inventario', '0008_producto_tipo_producto_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='inventario.almacen', verbose_name='Almacén Destino'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='inventario.almacen', verbose_name='Almacén Origen'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='inventario_actual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Inventario Actual'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='inventario_anterior',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Inventario Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden_produccion_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Orden Producción'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo_inventario',
            field=models.CharField(choices=[('materia_prima', 'Materia Prima'), ('producto_terminado', 'Producto Terminado'), ('general', 'General')], default='general', max_length=30, verbose_name='Tipo de Inventario'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_documento',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste de Inventario'), ('devolucion_compra', 'Devolución de Compra'), ('devolucion_venta', 'Devolución de Venta'), ('transferencia', 'Transferencia'), ('inventario_inicial', 'Inventario Inicial'), ('orden_produccion', 'Orden de Producción'), ('recepcion_produccion', 'Recepción de Producción')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_entrada', 'Ajuste - Entrada'), ('ajuste_salida', 'Ajuste - Salida'), ('devolucion_compra', 'Devolución Compra'), ('devolucion_venta', 'Devolución Venta'), ('transferencia_entrada', 'Transferencia - Entrada'), ('transferencia_salida', 'Transferencia - Salida'), ('entrada_compra', 'Entrada por Compra'), ('salida_produccion', 'Salida a Producción'), ('entrada_produccion', 'Entrada por Producción'), ('salida_venta', 'Salida por Venta'), ('reserva_produccion', 'Reserva para Producción'), ('liberacion_reserva', 'Liberación de Reserva'), ('reserva_venta', 'Reserva para Venta')], max_length=30),
        ),
        migrations.CreateModel(
            name='InventarioProductosTerminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=4, default=0, help_text='Stock disponible para venta', max_digits=12, verbose_name='Cantidad Disponible')),
                ('cantidad_reservada', models.DecimalField(decimal_places=4, default=0, help_text='Stock reservado para ventas pendientes', max_digits=12, verbose_name='Cantidad Reservada')),
                ('costo_produccion_unitario', models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio de producción por unidad', max_digits=12, verbose_name='Costo de Producción Unitario')),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Precio de Venta Sugerido')),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Almacén')),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stock Máximo')),
                ('lote_produccion', models.CharField(blank=True, max_length=100, verbose_name='Lote de Producción')),
                ('fecha_produccion', models.DateField(blank=True, null=True, verbose_name='Fecha de Producción')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('orden_produccion_id', models.IntegerField(blank=True, null=True, verbose_name='ID Orden de Producción')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo_producto': 'FINISHED'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_productos_terminados', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Inventario de Producto Terminado',
                'verbose_name_plural': 'Inventarios de Productos Terminados',
                'ordering': ['producto__nombre'],
                'indexes': [models.Index(fields=['empresa', 'producto'], name='inventario__empresa_eb093d_idx'), models.Index(fields=['empresa', 'almacen'], name='inventario__empresa_d0f68b_idx'), models.Index(fields=['fecha_produccion'], name='inventario__fecha_p_4c6ba4_idx'), models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_89af91_idx')],
                'unique_together': {('empresa', 'producto', 'almacen', 'lote_produccion')},
            },
        ),
        migrations.CreateModel(
            name='InventarioMateriasPrimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=4, default=0, help_text='Stock disponible para uso', max_digits=12, verbose_name='Cantidad Disponible')),
                ('cantidad_reservada', models.DecimalField(decimal_places=4, default=0, help_text='Stock reservado para producción en proceso', max_digits=12, verbose_name='Cantidad Reservada')),
                ('costo_unitario_promedio', models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio ponderado', max_digits=12, verbose_name='Costo Unitario Promedio')),
                ('ubicacion_almacen', models.CharField(blank=True, help_text='Estante, pasillo, etc.', max_length=100, verbose_name='Ubicación en Almacén')),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stock Máximo')),
                ('lote', models.CharField(blank=True, max_length=100, verbose_name='Número de Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo_producto__in': ['RAW', 'SEMIFINISHED']}, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_materias_primas', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Inventario de Materia Prima',
                'verbose_name_plural': 'Inventarios de Materias Primas',
                'ordering': ['producto__nombre'],
                'indexes': [models.Index(fields=['empresa', 'producto'], name='inventario__empresa_16bbec_idx'), models.Index(fields=['empresa', 'almacen'], name='inventario__empresa_a493df_idx'), models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_17231e_idx')],
                'unique_together': {('empresa', 'producto', 'almacen', 'lote')},
            },
        ),
    ]
