# Generated by Django 4.2.7 on 2026-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_add_marca_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controla_stock',
            field=models.BooleanField(default=True, help_text='True: el producto mueve inventario. False: servicios/no inventariables (nunca reservan ni descuentan).', verbose_name='Controla stock'),
        ),
    ]
