# Generated by Django 4.2.7 on 2025-10-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mlmodel',
            name='unique_empresa_model_version',
        ),
        migrations.RenameIndex(
            model_name='mlmodel',
            new_name='ml_models_m_empresa_07d613_idx',
            old_name='ml_models_m_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='mlprediction',
            new_name='ml_models_m_model_i_a69bc2_idx',
            old_name='ml_models_m_model_i_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('empresa', 'model_type', 'version')},
        ),
    ]
