# Generated by Django 4.2.7 on 2025-05-30 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_sku_alter_categoria_unique_together_and_more'),
        ('compras', '0003_add_comprobante_to_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compradetalle',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compra'},
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pagos/'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('pendiente', 'Pendiente')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de operación, cheque, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
