# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compradetalle_options_compradetalle_created_at_and_more'),
    ]

    operations = [
        # Migración vacía - los cambios ya se aplicaron manualmente
    ]
