# Generated by Django 4.2.7 on 2025-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_fix_comprarecurrente_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.CharField(
                choices=[('PEN', 'Sol Peruano (S/)'), ('USD', 'Dólar Americano ($)')],
                default='PEN',
                max_length=3,
                verbose_name='Moneda'
            ),
        ),
    ]
