# Generated by Django 4.2.7 on 2025-06-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('compras', '0006_add_moneda_to_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterUniqueTogether(
            name='comprarecurrente',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='comprarecurrente',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'Sol Peruano (S/)'), ('USD', 'Dólar Americano ($)')], default='PEN', max_length=3, verbose_name='Moneda del pago'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comprarecurrente',
            unique_together={('empresa', 'proveedor_nombre', 'concepto')},
        ),
        migrations.DeleteModel(
            name='OrdenCompraDetalle',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='dia_pago',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='fecha_ultima_compra',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='igv_incluido',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='ultima_compra',
        ),
        migrations.RemoveField(
            model_name='comprarecurrente',
            name='updated_at',
        ),
    ]
