# Generated by Django 4.2.7 on 2026-02-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
        ('compras', '0007_add_moneda_to_pagocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('empresa', 'numero')},
        ),
    ]
