# Generated by Django 4.2.9 on 2026-06-04 15:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_fix_ordencompra_fecha_actualizacion_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Orden de Compra',
                'db_table': 'compras_ordencompradetalle',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
