# Generated by Django 4.2.7 on 2026-06-20 14:12

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_tipo_cambio_usd'),
        ('compras', '0016_oc_contacto_nombre_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicioCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('moneda', models.CharField(choices=[('PEN', 'Sol Peruano (S/)'), ('USD', 'Dólar Americano ($)')], default='USD', max_length=3)),
                ('forma_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('igv_incluido', models.BooleanField(default=False)),
                ('porcentaje_igv', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio_compra', to='empresas.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio_compra', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra de Servicio',
                'verbose_name_plural': 'Órdenes de Compra de Servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemServicioCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(default=1)),
                ('numero_serie', models.CharField(blank=True, max_length=120, null=True)),
                ('modelo', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=120, null=True)),
                ('trabajo', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordenserviciocompra')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra de Servicio',
                'verbose_name_plural': 'Ítems de Orden de Compra de Servicio',
                'ordering': ['numero_item', 'id'],
            },
        ),
    ]
