# Generated by Django 4.2.7 on 2026-09-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_contacto_nombre_email'),
        ('ventas', '0017_detalleventa_descripcion_detalleventa_origen_and_more'),
        ('compras', '0017_ordenserviciocompra_itemserviciocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='cotizaciones.cotizacion'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='ventas.venta'),
        ),
    ]
