# Generated by Django 4.2.7 on 2026-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_ordencompra_cotizacion_origen_ordencompra_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_ordencompra_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='ordenserviciocompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_ordscompra_empresa_numero'),
        ),
    ]
